# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Minh Thanh Tran Le
title: Freshman
email: mailto:minhthanhz1516@gmail.com
website: https://github.com/minhthanh224

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: minhthanh224
linkedin_username: Tran Le Minh Thanh

# Additional icon links
additional_links:
  - title: GitHub Portfolio
    icon: fab fa-github
    url: https://github.com/minhthanh224

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Thanh and I'm currently studying as a Freshman at the University of Information Technology - Vietnam National University.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Personal Website
        link: https://github.com/minhthanh224
        link_text: View Project
        description: | # this will include new lines to allow paragraphs
          A personal website using the template by sproogen

  - title: Education
    layout: list
    content:
      - layout: left
        title: Tien Giang High School for the Gifted
        caption: 2021 - 2024
        description: | # this will include new lines to allow paragraphs
          Focused on my math and english skills.
      - layout: left
        title: University of Information Technology - VNU
        caption: 2024 - Present
        sub_title: BSc in Computer Science
        description: | # this will include new lines to allow paragraphs
          Currently pursuing a degree in Computer Science, with a focus on software engineering and AI.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Outside of my studies, I enjoy exploring new programming language.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
